### PR TITLE
Login Fixed

### PR DESCRIPTION
**Pull request by Chirag-varu**
This pull request addresses and resolves all reported bugs and issues in the login component

just make sure:-
in Login.tsx file there is ./login.css change it to ./Login.css :)

### CODE REVIEW

**Comment by Chirag-varu** [comment]
This pull request addresses and resolves all reported bugs and issues in the login component

just make sure:-
in Login.tsx file there is ./login.css change it to ./Login.css :)

**Comment by Chirag-varu** [comment]
just make sure:-
in Login.tsx file there is ./login.css change it to ./Login.css :)

**Review by shahkushal38 — APPROVED** [review]
approved

**Comment by Chirag-varu** [comment]
Thanks

**Pull request merged**
